# Build settings

port: 4000
markdown: kramdown
permalink: /:title
plugins: [jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title: "Sohae"
description: "Powered by Jekyll and GitHub Pages"
author: "Sohae Kim"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge