---
#-------------------------------
# General Site Settings

menu:
  - { name: "About", url: "about" }
  - { name: "Stack", url: "stack" }
  - { name: "Projects", url: "" }
  - { name: "Blog", url: "blog" }

#-------------------------------
# Projects Section

projects:
  - { name: "브릭챗", url: "proj-4" }
  - { name: "MEDIKIT", url: "medikit" }
  - { name: "knock!綠!", url: "knock" }
  - { name: "Bit library", url: "proj-1" }
  # - { name: "To-do List", url: "proj-2" }
  # - { name: "coming soon", url: "proj-3" }
  # - { name: "coming soon", url: "proj-5" }

#-------------------------------
# Contact Section

social:
  - { icon: "github", link: "https://github.com/dayook" }
  # - { icon: "linkedin", link: "https://linkedin.com/in/lenpaul" }

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: "Personal portfolio powered by Jekyll and GitHub Pages "
  rel-author: "https://plus.google.com/u/0/#"
  rel-publisher: "https://plus.google.com/u/0/#"

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: "UA-112060364-3"

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ""
